# Generated by Django 3.2.22 on 2023-10-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animieapp', '0002_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='cpass',
            field=models.CharField(default='default_value_here', max_length=50),
        ),
    ]
