# Generated by Django 3.2.22 on 2023-10-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animieapp', '0003_signup_cpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='email',
            field=models.EmailField(default='default_value', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='first_name',
            field=models.CharField(default='default_value', max_length=50),
        ),
        migrations.AddField(
            model_name='signup',
            name='second_name',
            field=models.CharField(default='default_value', max_length=50),
        ),
        migrations.AlterField(
            model_name='signup',
            name='cpass',
            field=models.CharField(default='default_value', max_length=50),
        ),
    ]
