# Generated by Django 3.2.22 on 2023-10-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animieapp', '0005_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Signups',
        ),
    ]
