# Generated by Django 3.2.22 on 2023-10-28 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animieapp', '0007_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Video',
            field=models.FileField(upload_to='vdeo'),
        ),
    ]
